// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhewNIrK8DgSkoQAwh9KOcBnXX3NMDG0w',
    appId: '1:884532110716:android:995283126643c5c2e770f9',
    messagingSenderId: '884532110716',
    projectId: 'e-commerce-edf4b',
    storageBucket: 'e-commerce-edf4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv5rsm3Wts7y9nSe0gjazMuw7FEdC87T4',
    appId: '1:884532110716:ios:fd0ae40f6156b46de770f9',
    messagingSenderId: '884532110716',
    projectId: 'e-commerce-edf4b',
    storageBucket: 'e-commerce-edf4b.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo4WfQSUBkQ8w11vm57bxSjNvgdy9ouYc',
    appId: '1:884532110716:web:bd2289346bff1276e770f9',
    messagingSenderId: '884532110716',
    projectId: 'e-commerce-edf4b',
    authDomain: 'e-commerce-edf4b.firebaseapp.com',
    storageBucket: 'e-commerce-edf4b.firebasestorage.app',
    measurementId: 'G-72QPG1XDWV',
  );
}
